name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Godot project
        uses: barichello/godot-ci@v4.3.0
        with:
          name: ShadowFiles
          preset: Android
